/**
 * Map validated agent files onto the first-party `dsh-tool-subagent` config.
 *
 * Two hazards drive this module:
 * - **Scoped tools shadow globals silently** (`packages/core/tools/src/index.ts:1021-1024`),
 *   so a generated name is checked against the effective pre-mount tool-name
 *   universe and a conflict skips the file rather than hijacking a core tool.
 * - **Direct `apply()` bypasses Schemastery defaults**
 *   (`packages/subagent/tool-subagent/src/index.ts:313-316`), so `maxDepth` is
 *   always emitted explicitly; an omission would be capless.
 *
 * @module dsh-project-agents/config-mapping
 */

import { ReasoningEffortId } from '@deepseek-ai/dsh-llm'
import type { Config as SubagentToolConfig } from '@deepseek-ai/dsh-tool-subagent'
import { renderSurfacedDiagnostics } from './diagnostics.ts'
import type { DiagnosticSink } from './diagnostics.ts'
import type { Diagnostic, DiscoveredAgentFile, ResolvedAgent } from './types.ts'

export type { SubagentToolConfig }

/** Mandatory namespace for every generated model-facing tool name. */
export const TOOL_NAME_PREFIX = 'agent_'

/** Reserved transport name that may never be registered as an ordinary tool. */
export const RESERVED_TOOL_NAME = 'run_code'

/**
 * Derive the model-facing tool name for an agent name.
 * @param name - the validated agent name.
 * @returns the namespaced tool name.
 */
export function toolNameFor(name: string): string {
  return `${TOOL_NAME_PREFIX}${name.replace(/-/g, '_')}`
}

/**
 * Resolve discovered files into the internal resolved schema, rejecting every
 * name that would collide inside the roster or shadow an existing tool.
 * @param files - discovered, frontmatter-validated files.
 * @param existingToolNames - the effective pre-mount tool-name universe for the
 *   target Agent scope; empty when the tool registry cannot be read.
 * @param sink - diagnostics accumulator for skipped files.
 * @returns the immutable resolved roster.
 */
export function resolveAgents(
  files: readonly DiscoveredAgentFile[],
  existingToolNames: ReadonlySet<string>,
  sink: DiagnosticSink,
): readonly ResolvedAgent[] {
  const resolved: ResolvedAgent[] = []
  const takenToolNames = new Map<string, string>()
  for (const file of files) {
    const toolName = toolNameFor(file.fields.name)
    if (toolName === RESERVED_TOOL_NAME) {
      sink.add({
        severity: 'error',
        path: file.path,
        field: 'name',
        reason: `generates the reserved tool name "${RESERVED_TOOL_NAME}"`,
      })
      continue
    }
    const clash = takenToolNames.get(toolName)
    if (clash !== undefined) {
      sink.add({
        severity: 'error',
        path: file.path,
        field: 'name',
        reason: `tool name "${toolName}" is already generated by ${clash} — agent names that differ only by "-" vs "_" collide`,
      })
      continue
    }
    if (existingToolNames.has(toolName)) {
      sink.add({
        severity: 'error',
        path: file.path,
        field: 'name',
        reason: `tool name "${toolName}" already exists in this Agent's scope; mounting it would silently shadow that tool`,
      })
      continue
    }
    takenToolNames.set(toolName, file.path)
    resolved.push({
      name: file.fields.name,
      slug: toolName.slice(TOOL_NAME_PREFIX.length),
      toolName,
      description: file.fields.description,
      transport: file.fields.transport,
      persona: file.fields.persona,
      maxDepth: file.fields.maxDepth,
      background: file.fields.background,
      path: file.path,
      layer: file.layer,
      ...(file.fields.llm === undefined ? {} : { llm: file.fields.llm }),
      ...(file.fields.tools === undefined ? {} : { toolFilter: file.fields.tools }),
    })
  }
  return resolved
}

/**
 * Project one resolved agent onto the first-party delegation-tool config.
 * @param agent - one resolved agent.
 * @returns the config to hand to `ToolSubagent.apply`.
 */
export function toSubagentConfig(agent: ResolvedAgent): SubagentToolConfig {
  return {
    // `transport` names the ctx.subagents provider; `llm.provider` names the LLM
    // route. Conflating them under one `provider` key would route the wrong layer.
    provider: agent.transport,
    toolName: agent.toolName,
    // Per-agent models are fixed by the markdown; runtime override would add
    // three parameters to every tool schema for no requested benefit.
    modelSelectionSettings: false,
    backgroundMode: agent.background,
    persona: agent.persona,
    // Always explicit: a direct-apply omission stays capless.
    maxDepth: agent.maxDepth,
    ...(agent.llm === undefined
      ? {}
      : {
          agentOptions: {
            provider: agent.llm.provider,
            model: agent.llm.model,
            ...(agent.llm.reasoningEffort === undefined
              ? {}
              : { reasoningEffort: ReasoningEffortId(agent.llm.reasoningEffort) }),
          },
        }),
    ...(agent.toolFilter === undefined
      ? {}
      : {
          toolFilter: {
            ...(agent.toolFilter.allow === undefined ? {} : { allow: [...agent.toolFilter.allow] }),
            ...(agent.toolFilter.deny === undefined ? {} : { deny: [...agent.toolFilter.deny] }),
          },
        }),
  }
}

/** Capability surface this plugin reads off a `ctx.subagents` provider. */
export interface ProviderCapabilityView {
  readonly capabilities: {
    readonly agentOptions?: boolean
    readonly depthLimit?: boolean
  }
  readonly prepareContinuable?: unknown
}

/**
 * Check a resolved agent against the transport it selected.
 *
 * `agentOptions` requires the provider's `agentOptions` capability and a
 * numeric `maxDepth` requires `depthLimit`; `ToolSubagent.apply` throws on
 * either mismatch, and a throw from inside an Agent-scoped fiber is far worse
 * than a skipped file with a diagnostic.
 * @param agent - one resolved agent.
 * @param provider - the registered provider, or undefined when it has not
 *   appeared yet (registration is deferred, so absence is not a rejection).
 * @returns the rejection reason, or undefined when the mount is admissible.
 */
export function capabilityRejection(
  agent: ResolvedAgent,
  provider: ProviderCapabilityView | undefined,
): string | undefined {
  if (provider === undefined) return undefined
  if (agent.llm !== undefined && provider.capabilities.agentOptions !== true) {
    return `transport "${agent.transport}" does not support child agentOptions, so \`llm.*\` cannot be applied`
  }
  if (typeof agent.maxDepth === 'number' && provider.capabilities.depthLimit !== true) {
    return `transport "${agent.transport}" cannot enforce a numeric maxDepth (no depthLimit capability); use maxDepth: provider-managed`
  }
  if (agent.background === 'continuable' && provider.prepareContinuable === undefined) {
    return `transport "${agent.transport}" does not support background: continuable`
  }
  return undefined
}

/**
 * Render the Agent-scoped catalog section body.
 *
 * The first-party tool description is generic per transport and background
 * mode (`packages/subagent/tool-subagent/src/index.ts:365-388`), so two
 * instances are textually identical apart from `toolName`. Without this the
 * parent model cannot route among them.
 *
 * The same section carries the surfaced diagnostics, because this plugin owns
 * no tool and the shipped `web` profile mounts no log exporter: the model is
 * otherwise the only party that can explain a missing agent to the operator,
 * and it has to be told. The block is emitted even when nothing mounted, which
 * is precisely the case the log alone failed to make visible.
 * @param agents - the agents whose tools actually mounted.
 * @param diagnostics - every diagnostic recorded for this roster.
 * @returns the section text, or the empty string when there is nothing to say.
 */
export function renderCatalog(
  agents: readonly ResolvedAgent[],
  diagnostics: readonly Diagnostic[] = [],
): string {
  const surfaced = renderSurfacedDiagnostics(diagnostics)
  if (agents.length === 0 && surfaced.length === 0) return ''
  const parts: string[] = []
  if (agents.length > 0) {
    parts.push(
      'Project-scoped subagents available in this working directory. Each is a separate',
      'delegation tool with its own persona, model route and tool access; their generic',
      'tool descriptions are identical, so choose between them by the roles below.',
      '',
      ...agents.map(agent => `- \`${agent.toolName}\` — ${agent.description}`),
    )
  }
  if (surfaced.length > 0) {
    if (parts.length > 0) parts.push('')
    parts.push(
      'Markdown agent definitions in this working directory were skipped and are NOT',
      'available as delegation tools. Tell the operator which files below need fixing:',
      ...surfaced,
    )
  }
  return parts.join('\n')
}
