/**
 * Map validated agent files onto the first-party `dsh-tool-subagent` config.
 *
 * Two hazards drive this module:
 * - **Scoped tools shadow globals silently** (`packages/core/tools/src/index.ts:1021-1024`),
 *   so a generated name is checked against the effective pre-mount tool-name
 *   universe and a conflict skips the file rather than hijacking a core tool.
 * - **Direct `apply()` bypasses Schemastery defaults**
 *   (`packages/subagent/tool-subagent/src/index.ts:313-316`), so `maxDepth` is
 *   always emitted explicitly; an omission would be capless.
 *
 * @module dsh-project-context/config-mapping
 */

import { ReasoningEffortId } from '@deepseek-ai/dsh-llm'
import type { Config as SubagentToolConfig } from '@deepseek-ai/dsh-tool-subagent'
import { renderSurfacedDiagnostics } from './diagnostics.ts'
import type { DiagnosticSink } from './diagnostics.ts'
import type { Diagnostic, DiscoveredAgentFile, ResolvedAgent } from './types.ts'

export type { SubagentToolConfig }

/** Mandatory namespace for every generated model-facing tool name. */
export const TOOL_NAME_PREFIX = 'agent_'

/** Reserved transport name that may never be registered as an ordinary tool. */
export const RESERVED_TOOL_NAME = 'run_code'

/**
 * Derive the model-facing tool name for an agent name.
 * @param name - the validated agent name.
 * @returns the namespaced tool name.
 */
export function toolNameFor(name: string): string {
  return `${TOOL_NAME_PREFIX}${name.replace(/-/g, '_')}`
}

/**
 * Resolve discovered files into the internal resolved schema, rejecting every
 * name that would collide inside the roster or shadow an existing tool.
 * @param files - discovered, frontmatter-validated files.
 * @param existingToolNames - the effective pre-mount tool-name universe for the
 *   target Agent scope; empty when the tool registry cannot be read.
 * @param sink - diagnostics accumulator for skipped files.
 * @returns the immutable resolved roster.
 */
export function resolveAgents(
  files: readonly DiscoveredAgentFile[],
  existingToolNames: ReadonlySet<string>,
  sink: DiagnosticSink,
): readonly ResolvedAgent[] {
  const resolved: ResolvedAgent[] = []
  const takenToolNames = new Map<string, string>()
  for (const file of files) {
    const toolName = toolNameFor(file.fields.name)
    if (toolName === RESERVED_TOOL_NAME) {
      sink.add({
        severity: 'error',
        path: file.path,
        field: 'name',
        reason: `generates the reserved tool name "${RESERVED_TOOL_NAME}"`,
      })
      continue
    }
    const clash = takenToolNames.get(toolName)
    if (clash !== undefined) {
      sink.add({
        severity: 'error',
        path: file.path,
        field: 'name',
        reason: `tool name "${toolName}" is already generated by ${clash} — agent names that differ only by "-" vs "_" collide`,
      })
      continue
    }
    if (existingToolNames.has(toolName)) {
      sink.add({
        severity: 'error',
        path: file.path,
        field: 'name',
        reason: `tool name "${toolName}" already exists in this Agent's scope; mounting it would silently shadow that tool`,
      })
      continue
    }
    takenToolNames.set(toolName, file.path)
    resolved.push({
      name: file.fields.name,
      slug: toolName.slice(TOOL_NAME_PREFIX.length),
      toolName,
      description: file.fields.description,
      transport: file.fields.transport,
      persona: file.fields.persona,
      maxDepth: file.fields.maxDepth,
      background: file.fields.background,
      path: file.path,
      layer: file.layer,
      ...(file.fields.llm === undefined ? {} : { llm: file.fields.llm }),
      ...(file.fields.tools === undefined ? {} : { toolFilter: file.fields.tools }),
    })
  }
  return resolved
}

/**
 * Project one resolved agent onto the first-party delegation-tool config.
 * @param agent - one resolved agent.
 * @returns the config to hand to `ToolSubagent.apply`.
 */
export function toSubagentConfig(agent: ResolvedAgent): SubagentToolConfig {
  return {
    // `transport` names the ctx.subagents provider; `llm.provider` names the LLM
    // route. Conflating them under one `provider` key would route the wrong layer.
    provider: agent.transport,
    toolName: agent.toolName,
    // Per-agent models are fixed by the markdown; runtime override would add
    // three parameters to every tool schema for no requested benefit.
    modelSelectionSettings: false,
    backgroundMode: agent.background,
    persona: agent.persona,
    // Always explicit: a direct-apply omission stays capless.
    maxDepth: agent.maxDepth,
    ...(agent.llm === undefined
      ? {}
      : {
          agentOptions: {
            provider: agent.llm.provider,
            model: agent.llm.model,
            ...(agent.llm.reasoningEffort === undefined
              ? {}
              : { reasoningEffort: ReasoningEffortId(agent.llm.reasoningEffort) }),
          },
        }),
    ...(agent.toolFilter === undefined
      ? {}
      : {
          toolFilter: {
            ...(agent.toolFilter.allow === undefined ? {} : { allow: [...agent.toolFilter.allow] }),
            ...(agent.toolFilter.deny === undefined ? {} : { deny: [...agent.toolFilter.deny] }),
          },
        }),
  }
}

/** Capability surface this plugin reads off a `ctx.subagents` provider. */
export interface ProviderCapabilityView {
  readonly capabilities: {
    readonly agentOptions?: boolean
    readonly depthLimit?: boolean
  }
  readonly prepareContinuable?: unknown
}

/**
 * Check a resolved agent against the transport it selected.
 *
 * `agentOptions` requires the provider's `agentOptions` capability and a
 * numeric `maxDepth` requires `depthLimit`; `ToolSubagent.apply` throws on
 * either mismatch, and a throw from inside an Agent-scoped fiber is far worse
 * than a skipped file with a diagnostic.
 * @param agent - one resolved agent.
 * @param provider - the registered provider, or undefined when it has not
 *   appeared yet (registration is deferred, so absence is not a rejection).
 * @returns the rejection reason, or undefined when the mount is admissible.
 */
export function capabilityRejection(
  agent: ResolvedAgent,
  provider: ProviderCapabilityView | undefined,
): string | undefined {
  if (provider === undefined) return undefined
  if (agent.llm !== undefined && provider.capabilities.agentOptions !== true) {
    return `transport "${agent.transport}" does not support child agentOptions, so \`llm.*\` cannot be applied`
  }
  if (typeof agent.maxDepth === 'number' && provider.capabilities.depthLimit !== true) {
    return `transport "${agent.transport}" cannot enforce a numeric maxDepth (no depthLimit capability); use maxDepth: provider-managed`
  }
  if (agent.background === 'continuable' && provider.prepareContinuable === undefined) {
    return `transport "${agent.transport}" does not support background: continuable`
  }
  return undefined
}

/**
 * The Agent's own position against the project-scoped delegation caps, carried
 * by the catalog section when no mounted tool can accept a child.
 *
 * Every mounted numeric cap is exceeded whenever this value exists, so
 * `maxDepth` — the largest one — is the strongest true statement about the whole
 * mounted set, and it is the same `maxDepth` this plugin wrote into each tool
 * config ({@link toSubagentConfig}).
 */
export interface DelegationCapNotice {
  /** The Agent's own delegation depth. */
  readonly depth: number
  /** The largest numeric `maxDepth` among the mounted delegation tools. */
  readonly maxDepth: number
}

/**
 * Decide whether the mounted project-scoped delegation tools can accept a child
 * from an Agent at `depth`.
 *
 * `depth` is the monotone FLOOR the session header records, never the full
 * runtime value: `header + 1 > cap` implies `actual + 1 > cap`, so reading the
 * header can only MISS a notice, never over-claim one. `delegationDepthOf` is
 * deliberately unused — it throws on an invalid runtime value
 * (`packages/subagent/subagent/src/depth.ts:30-32`) and the only caller runs
 * during prompt assembly, where a throw breaks the whole request.
 *
 * The claim is scoped to the tools it names: a `'provider-managed'` cap never
 * counts as reached, because such a tool hands core no cap at all
 * (`resolveMaxDepth` returns `undefined`) and delegation through it can still
 * succeed. Degrading to no notice is the conservative direction — a false
 * "unusable" would instruct the model away from a call that works.
 * @param agents - the mounted agents, in catalog order.
 * @param depth - the Agent's delegation depth.
 * @returns the declaration input, or undefined when a child is still possible.
 */
export function delegationCapNotice(
  agents: readonly ResolvedAgent[],
  depth: number,
): DelegationCapNotice | undefined {
  const blocked = agents.length > 0
    && agents.every(entry => typeof entry.maxDepth === 'number' && depth + 1 > entry.maxDepth)
  if (!blocked) return undefined
  const caps = agents
    .map(entry => entry.maxDepth)
    .filter((cap): cap is number => typeof cap === 'number')
  return { depth, maxDepth: Math.max(...caps) }
}

/**
 * Render the Agent-scoped catalog section body.
 *
 * The first-party tool description is generic per transport and background
 * mode (`packages/subagent/tool-subagent/src/index.ts:365-388`), so two
 * instances are textually identical apart from `toolName`. Without this the
 * parent model cannot tell them apart at all.
 *
 * The block is a DECLARATION, not a policy: it states which agents exist and
 * what each is for, and stops there. When to delegate, and to which agent, is
 * project policy that belongs in a rule file under `.dsh/rules` — text that
 * can change without rebuilding this plugin. Keep usage instructions out of
 * here; only the diagnostics block below is allowed to instruct, because it is
 * a delivery channel for per-file failures no static rule file could name.
 *
 * The same section carries the surfaced diagnostics, because this plugin owns
 * no tool and the shipped `web` profile mounts no log exporter: the model is
 * otherwise the only party that can explain a missing agent to the operator,
 * and it has to be told. The block is emitted even when nothing mounted, which
 * is precisely the case the log alone failed to make visible.
 *
 * A `notice` opens the section with a second declaration of PER-SESSION state:
 * that the tools listed beneath it will reject a call from this session. It
 * belongs in the same section for the diagnostics channel's own reason — no
 * static rule file can know this Agent's depth — and it adds no instruction, so
 * the diagnostics block stays the only instructing channel. Depth 0 never
 * carries one, which keeps that prompt prefix byte-identical for KV cache.
 * @param agents - the agents whose tools actually mounted.
 * @param diagnostics - every diagnostic recorded for this roster.
 * @param notice - the Agent's delegation-cap declaration, when no mounted tool
 *   can accept a child from this session.
 * @returns the section text, or the empty string when there is nothing to say.
 */
export function renderCatalog(
  agents: readonly ResolvedAgent[],
  diagnostics: readonly Diagnostic[] = [],
  notice?: DelegationCapNotice,
): string {
  const surfaced = renderSurfacedDiagnostics(diagnostics)
  if (agents.length === 0 && surfaced.length === 0) return ''
  const parts: string[] = []
  if (agents.length > 0 && notice !== undefined) {
    parts.push(
      'The project-scoped delegation tools listed below cannot be called from this',
      `session: it is already ${notice.depth} levels of delegation deep, and they allow`,
      `delegation up to ${notice.maxDepth} levels. Any call will be rejected, and that will`,
      'not change for the rest of this session.',
      '',
    )
  }
  if (agents.length > 0) {
    parts.push(
      'Project-scoped subagents declared in this working directory. Each is a separate',
      'delegation tool with its own persona, model route and tool access.',
      '',
      ...agents.map(agent => `- \`${agent.toolName}\` — ${agent.description}`),
    )
  }
  if (surfaced.length > 0) {
    if (parts.length > 0) parts.push('')
    parts.push(
      'Markdown agent definitions in this working directory were skipped and are NOT',
      'available as delegation tools. Tell the operator which files below need fixing:',
      ...surfaced,
    )
  }
  return parts.join('\n')
}
