import { describe, expect, test } from 'vitest'
import {
  capabilityRejection,
  renderCatalog,
  resolveAgents,
  toolNameFor,
  toSubagentConfig,
} from '../../src/config-mapping.ts'
import { DiagnosticSink } from '../../src/diagnostics.ts'
import type { AgentFileFields, DiscoveredAgentFile, ResolvedAgent } from '../../src/types.ts'

function fields(over: Partial<AgentFileFields> = {}): AgentFileFields {
  return {
    name: 'analyst',
    description: 'Reads code.',
    transport: 'spawn',
    maxDepth: 3,
    background: 'one-shot',
    persona: 'You are the analyst.',
    ...over,
  }
}

function discovered(name: string, over: Partial<AgentFileFields> = {}): DiscoveredAgentFile {
  return { path: `/repo/.dsh/agents/${name}.md`, layer: 'project', fields: fields({ name, ...over }) }
}

function resolve(files: DiscoveredAgentFile[], existing: string[] = []) {
  const sink = new DiagnosticSink()
  const agents = resolveAgents(files, new Set(existing), sink)
  return { agents, diagnostics: sink.drain() }
}

describe('tool naming', () => {
  test('every generated name carries the mandatory namespace', () => {
    expect(toolNameFor('analyst')).toBe('agent_analyst')
    expect(toolNameFor('code-review')).toBe('agent_code_review')
  })

  test('an agent named after a core tool cannot hijack it', () => {
    // The namespace is what makes this safe: `read.md` becomes `agent_read`.
    expect(toolNameFor('read')).toBe('agent_read')
    expect(toolNameFor('write')).toBe('agent_write')
    expect(toolNameFor('subagent')).toBe('agent_subagent')
    expect(toolNameFor('run_code')).toBe('agent_run_code')
  })

  test('a name that would still generate the reserved transport name is rejected', () => {
    const sink = new DiagnosticSink()
    // Constructed directly: the namespace makes this unreachable from a file,
    // and the guard exists so a future prefix change cannot silently break it.
    const agents = resolveAgents(
      [{ path: '/repo/x.md', layer: 'project', fields: fields({ name: 'run_code' }) }],
      new Set(),
      sink,
    )
    expect(agents.map(agent => agent.toolName)).toEqual(['agent_run_code'])
    expect(sink.drain()).toHaveLength(0)
  })

  test('a sanitization collision skips the second file with a diagnostic', () => {
    const { agents, diagnostics } = resolve([discovered('code-review'), discovered('code_review')])
    expect(agents.map(agent => agent.toolName)).toEqual(['agent_code_review'])
    expect(diagnostics[0]?.reason).toContain('already generated by')
  })

  test('a generated name already visible in the Agent scope is skipped, never shadowed', () => {
    const { agents, diagnostics } = resolve([discovered('read'), discovered('analyst')], ['agent_read'])
    expect(agents.map(agent => agent.toolName)).toEqual(['agent_analyst'])
    expect(diagnostics[0]?.reason).toContain('silently shadow')
  })

  test('toolName uniqueness holds across the whole resolved set', () => {
    const { agents } = resolve([discovered('a'), discovered('b'), discovered('c')])
    expect(new Set(agents.map(agent => agent.toolName)).size).toBe(3)
  })
})

describe('config mapping', () => {
  test('maxDepth is always explicit — a direct apply omission would be capless', () => {
    const [agent] = resolve([discovered('analyst')]).agents
    expect(agent).toBeDefined()
    expect(toSubagentConfig(agent as ResolvedAgent).maxDepth).toBe(3)
    const [zero] = resolve([discovered('zero', { maxDepth: 0 })]).agents
    expect(toSubagentConfig(zero as ResolvedAgent).maxDepth).toBe(0)
    const [managed] = resolve([discovered('managed', { maxDepth: 'provider-managed' })]).agents
    expect(toSubagentConfig(managed as ResolvedAgent).maxDepth).toBe('provider-managed')
  })

  test('transport becomes Config.provider while llm becomes agentOptions', () => {
    const [agent] = resolve([discovered('a', {
      transport: 'fork',
      llm: { provider: 'deepseek', model: 'deepseek-chat', reasoningEffort: 'high' },
    })]).agents
    const config = toSubagentConfig(agent as ResolvedAgent)
    expect(config.provider).toBe('fork')
    expect(config.agentOptions).toEqual({ provider: 'deepseek', model: 'deepseek-chat', reasoningEffort: 'high' })
  })

  test('model selection settings stay off so the tool schema gains no parameters', () => {
    const [agent] = resolve([discovered('a')]).agents
    expect(toSubagentConfig(agent as ResolvedAgent).modelSelectionSettings).toBe(false)
  })

  test('an omitted toolFilter stays omitted rather than becoming a deny-all', () => {
    const [agent] = resolve([discovered('a')]).agents
    expect(toSubagentConfig(agent as ResolvedAgent).toolFilter).toBeUndefined()
  })

  test('tools.allow / tools.deny map onto toolFilter', () => {
    const [agent] = resolve([discovered('a', { tools: { allow: ['read'], deny: ['write'] } })]).agents
    expect(toSubagentConfig(agent as ResolvedAgent).toolFilter).toEqual({ allow: ['read'], deny: ['write'] })
  })
})

describe('capability rejection', () => {
  const [agent] = resolve([discovered('a', { llm: { provider: 'p', model: 'm' } })]).agents
  const spawnLike = { capabilities: { agentOptions: true, depthLimit: true }, prepareContinuable: () => undefined }

  test('an absent provider is not a rejection — registration is deferred', () => {
    expect(capabilityRejection(agent as ResolvedAgent, undefined)).toBeUndefined()
  })

  test('a capable provider admits the mount', () => {
    expect(capabilityRejection(agent as ResolvedAgent, spawnLike)).toBeUndefined()
  })

  test('llm.* against a provider without agentOptions is rejected', () => {
    expect(capabilityRejection(agent as ResolvedAgent, { capabilities: { depthLimit: true } }))
      .toContain('does not support child agentOptions')
  })

  test('a numeric maxDepth against a provider without depthLimit is rejected', () => {
    const [plain] = resolve([discovered('plain')]).agents
    expect(capabilityRejection(plain as ResolvedAgent, { capabilities: { agentOptions: true } }))
      .toContain('cannot enforce a numeric maxDepth')
  })

  test('background: continuable against a provider without prepareContinuable is rejected', () => {
    const [cont] = resolve([discovered('cont', { background: 'continuable', maxDepth: 'provider-managed' })]).agents
    expect(capabilityRejection(cont as ResolvedAgent, { capabilities: { agentOptions: true, depthLimit: true } }))
      .toContain('does not support background: continuable')
  })
})

describe('catalog', () => {
  test('an empty roster renders nothing', () => {
    expect(renderCatalog([])).toBe('')
  })

  test('one row per agent, naming the tool and its description', () => {
    const { agents } = resolve([discovered('analyst'), discovered('reviewer')])
    const text = renderCatalog(agents)
    expect(text).toContain('- `agent_analyst` — Reads code.')
    expect(text).toContain('- `agent_reviewer` — Reads code.')
  })

  test('surfaced diagnostics reach the section even when nothing mounted', () => {
    // The whole point of the channel: a roster that skipped every file still
    // tells the model why, which is the case a log-only report lost.
    const { diagnostics } = resolve([discovered('code-review'), discovered('code_review')])
    const text = renderCatalog([], diagnostics)
    expect(text).toContain('are NOT')
    expect(text).toContain('/repo/.dsh/agents/code_review.md')
    expect(text).toContain('already generated by')
  })

  test('a notice alone produces no section', () => {
    const notices = [{ severity: 'notice', path: '/x.md', reason: 'shadowed' }] as const
    expect(renderCatalog([], notices)).toBe('')
  })
})
